name: 'Setup Rust'
description: 'Checkout repository, setup cache and toolchain'
inputs:
  toolchain:
    description: 'Rust toolchain'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-${{ inputs.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.toolchain }}-
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        profile: minimal
    - run: rustup component add --toolchain ${{ inputs.toolchain }} clippy rustfmt
      shell: bash
