[package]
name = "twir-deploy-notify"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"
pulldown-cmark = "0.9"
teloxide = { version = "0.12", default-features = false }
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
proptest = "1"
