name: Auto merge

on:
  workflow_run:
    workflows: ["CI", "Integration Tests"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine PR number
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests[0];
            core.setOutput('number', pr ? pr.number : '');
      - name: Merge primary PR
        if: steps.pr.outputs.number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "$PR" --rebase --delete-branch
        env:
          PR: ${{ steps.pr.outputs.number }}
      - name: Rebase and merge remaining PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for n in $(gh pr list --state open --json number -q '.[].number'); do
            if [ "$n" != "${{ steps.pr.outputs.number }}" ]; then
              gh pr checkout "$n"
              git pull --rebase origin main || continue
              git push --force-with-lease
              gh pr merge "$n" --rebase --delete-branch || true
            fi
          done
