name: Cancel PR CI

on:
  pull_request:
    types: [closed]

permissions:
  actions: write

jobs:
  cancel:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, {
              owner,
              repo,
              event: 'pull_request',
              per_page: 100,
            });
            for (const run of runs) {
              const prNums = run.pull_requests.map(pr => pr.number);
              if (prNums.includes(prNumber) && ['queued','in_progress','waiting'].includes(run.status)) {
                await github.rest.actions.cancelWorkflowRun({ owner, repo, run_id: run.id });
              }
            }
