- name: Send latest post to Telegram
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  run: |
    latest_post=$(ls twir/content/*-this-week-in-rust*.md | sort | tail -n1)
    last_sent=$(cat last_sent.txt 2>/dev/null || echo "")
    if [ "$latest_post" != "$last_sent" ]; then
      text=$(cat "$latest_post")
      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d "chat_id=${TELEGRAM_CHAT_ID}" \
        --data-urlencode "text=$text"
      echo "$latest_post" > last_sent.txt
      git config user.name github-actions
      git config user.email github-actions@github.com
      git add last_sent.txt
      git commit -m "Update last_sent.txt"
      git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
    else
      echo "No new release. Skipping Telegram notification."
    fi
