name: Send TWIR summary

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Checkout TWIR
        uses: actions/checkout@v4
        with:
          repository: rust-lang/this-week-in-rust
          path: twir

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Send latest post to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          latest_post=$(ls twir/content/*-this-week-in-rust*.md | sort | tail -n1)
          last_sent=$(cat last_sent.txt 2>/dev/null || echo "")
          if [ "$latest_post" != "$last_sent" ]; then
            rm -f output_*.md
            cargo run -- "$latest_post"
            for file in $(ls -v output_*.md 2>/dev/null); do
              text=$(cat "$file")
              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d "chat_id=${TELEGRAM_CHAT_ID}" \
                --data-urlencode "text=$text" \
                -d "parse_mode=MarkdownV2"
            done
            echo "$latest_post" > last_sent.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add last_sent.txt
          git commit -m "Update last_sent.txt"
          git pull --rebase
          git push
          else
            echo "No new release. Skipping Telegram notification."
          fi
