name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_PROGRESS_WHEN: never
    steps:
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: "1.88.0"
      - run: cargo fmt --quiet --all -- --check

  check:
    needs: fmt
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_PROGRESS_WHEN: never
    steps:
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: "1.88.0"
      - run: cargo check --quiet --all-targets --features integration

  clippy:
    needs: check
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_PROGRESS_WHEN: never
    steps:
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: "1.88.0"
      - run: cargo clippy --quiet --all-targets --features integration -- -D warnings

  test:
    needs: clippy
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_PROGRESS_WHEN: never
    steps:
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: "1.88.0"
      - run: cargo test --quiet --all-targets --features integration -- --test-threads=$(nproc)
