name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-integration-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-integration-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: rustup component add clippy rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo check --all-targets --features integration
      - run: cargo clippy --all-targets --features integration -- -D warnings
      - run: cargo test --all-targets --features integration -- --test-threads=$(nproc)
